[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["chmod +x mvnw", "./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"]

[start]
cmd = "java -jar target/*-runner.jar"
