FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-17 AS build
COPY --chown=quarkus:quarkus . /project
WORKDIR /project
RUN ./mvnw clean package -Dquarkus.package.type=uber-jar

FROM registry.access.redhat.com/ubi9/openjdk-17:1.15
COPY --from=build /project/target/*-runner.jar /work/application.jar
EXPOSE 8080
WORKDIR /work
CMD ["java", "-jar", "application.jar"]