FROM registry.access.redhat.com/ubi9/openjdk-21:1.21

WORKDIR /deployments

# Copia o arquivo JAR principal
COPY target/api-recycle-dev.jar /deployments/app.jar

# Configurações de execução
EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
CMD ["java", "-jar", "app.jar"]
