FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
COPY --chown=quarkus:quarkus . /project
WORKDIR /project
RUN ./mvnw clean package

FROM quay.io/quarkus/quarkus-micro-image:2.0
COPY --from=build /project/target/quarkus-app/quarkus-run.jar /work/app.jar
EXPOSE 8080
WORKDIR /work
CMD ["java", "-jar", "app.jar"]
